### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [KorotkovAlex/diff-in-time#1]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by KorotkovAlex** [comment]
Hello @geopic thanks for the offer!  I am really interested, because I don't have free time make it.

**Comment by geopic** [comment]
Good stuff @KorotkovAlex, I'll start on it now then.

**Comment by KorotkovAlex** [comment]
@geopic thx a lot for your help.
